"""
PDF Generator using reportlab.
"""
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT


BRAND_COLOR = colors.HexColor("#6366F1")
ACCENT_COLOR = colors.HexColor("#14B8A6")
DARK_BG = colors.HexColor("#1E293B")
LIGHT_GRAY = colors.HexColor("#F1F5F9")


def generate_pdf(filepath: str, title: str, content: str, data: dict) -> None:
    """
    Generate a styled PDF report.

    Args:
        filepath: Where to save the PDF
        title: Report title
        content: LLM-generated narrative text (markdown-like)
        data: Structured DB data for tables
    """
    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=1 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=24,
        textColor=BRAND_COLOR,
        spaceAfter=6,
        fontName="Helvetica-Bold",
    )
    heading1_style = ParagraphStyle(
        "Heading1Custom",
        parent=styles["Heading1"],
        fontSize=16,
        textColor=DARK_BG,
        spaceBefore=16,
        spaceAfter=8,
        fontName="Helvetica-Bold",
    )
    body_style = ParagraphStyle(
        "BodyCustom",
        parent=styles["Normal"],
        fontSize=10,
        leading=16,
        spaceAfter=8,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#64748B"),
        spaceAfter=20,
    )

    story = []

    # Header
    story.append(Paragraph("CollegeMS", ParagraphStyle("Brand", parent=styles["Normal"], fontSize=10, textColor=ACCENT_COLOR)))
    story.append(Spacer(1, 4))
    story.append(Paragraph(title, title_style))
    story.append(Paragraph(f"Generated on {datetime.now().strftime('%d %B %Y, %I:%M %p')}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=BRAND_COLOR))
    story.append(Spacer(1, 20))

    # Process content (simple markdown-like parsing)
    for line in content.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 6))
        elif line.startswith("## "):
            story.append(Paragraph(line[3:], heading1_style))
        elif line.startswith("# "):
            story.append(Paragraph(line[2:], heading1_style))
        elif line.startswith("- ") or line.startswith("* "):
            story.append(Paragraph(f"• {line[2:]}", body_style))
        elif line.startswith("**") and line.endswith("**"):
            bold_style = ParagraphStyle("Bold", parent=body_style, fontName="Helvetica-Bold")
            story.append(Paragraph(line[2:-2], bold_style))
        else:
            story.append(Paragraph(line, body_style))

    # Add department summary table if available
    dept_data = data.get("department_summary", [])
    if dept_data:
        story.append(Spacer(1, 20))
        story.append(Paragraph("Department Summary", heading1_style))

        table_data = [["Department", "Total Students", "Avg Attendance %", "Avg Marks %"]]
        for row in dept_data:
            table_data.append([
                str(row.get("department", "")),
                str(row.get("total_students", "")),
                f"{row.get('avg_attendance_pct', 0):.1f}%",
                f"{row.get('avg_marks_pct', 0):.1f}%",
            ])

        table = Table(table_data, colWidths=[2.5 * inch, 1.5 * inch, 1.8 * inch, 1.5 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BRAND_COLOR),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 10),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [LIGHT_GRAY, colors.white]),
            ("FONTSIZE", (0, 1), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("ALIGN", (1, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(table)

    # Footer
    story.append(Spacer(1, 30))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E1")))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "This report was generated by CollegeMS AI Platform. All statistics are sourced directly from the institutional database.",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#94A3B8")),
    ))

    doc.build(story)
