"""initial_migration

Revision ID: 95c2ea7c1de9
Revises: 
Create Date: 2026-06-04 08:52:30.443994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95c2ea7c1de9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_syllabus_subject', table_name='syllabus_units')
    op.drop_table('syllabus_units')
    op.drop_index('ix_department_metrics_id', table_name='department_metrics')
    op.drop_table('department_metrics')
    op.drop_index('idx_enrollments_sem', table_name='semester_enrollments')
    op.drop_index('idx_enrollments_student', table_name='semester_enrollments')
    op.drop_table('semester_enrollments')
    op.drop_index('ix_student_interventions_id', table_name='student_interventions')
    op.drop_table('student_interventions')
    op.drop_index('idx_timetable_faculty', table_name='timetable_slots')
    op.drop_index('idx_timetable_room', table_name='timetable_slots')
    op.drop_index('idx_timetable_semester', table_name='timetable_slots')
    op.drop_table('timetable_slots')
    op.drop_index('ix_department_reviews_id', table_name='department_reviews')
    op.drop_table('department_reviews')
    op.drop_index('idx_notif_unread', table_name='notifications', postgresql_where='(is_read = false)')
    op.drop_index('idx_notif_user', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_fsa_sem', table_name='faculty_subject_assignments')
    op.drop_index('idx_fsa_subject', table_name='faculty_subject_assignments')
    op.drop_index('idx_fsa_user', table_name='faculty_subject_assignments')
    op.drop_table('faculty_subject_assignments')
    op.drop_index('idx_risk_date', table_name='at_risk_snapshots')
    op.drop_index('idx_risk_high', table_name='at_risk_snapshots', postgresql_where='(risk_score >= (60)::numeric)')
    op.drop_index('idx_risk_student', table_name='at_risk_snapshots')
    op.drop_table('at_risk_snapshots')
    op.drop_index('idx_docs_student', table_name='student_documents')
    op.drop_table('student_documents')
    op.drop_index('ix_institution_metrics_id', table_name='institution_metrics')
    op.drop_table('institution_metrics')
    op.drop_table('program_semesters')
    op.drop_index('ix_executive_insights_id', table_name='executive_insights')
    op.drop_table('executive_insights')
    op.drop_index('idx_exams_date', table_name='exam_schedules')
    op.drop_index('idx_exams_semester', table_name='exam_schedules')
    op.drop_table('exam_schedules')
    op.drop_index('idx_audit_college', table_name='audit_logs')
    op.drop_index('idx_audit_table', table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_student_risk_scores_id', table_name='student_risk_scores')
    op.drop_table('student_risk_scores')
    op.drop_index('ix_communications_id', table_name='communications')
    op.drop_table('communications')
    op.drop_index('ix_accreditation_metrics_id', table_name='accreditation_metrics')
    op.drop_table('accreditation_metrics')
    op.drop_index('idx_chat_session', table_name='chat_sessions')
    op.drop_index('idx_chat_user', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('ix_review_action_items_id', table_name='review_action_items')
    op.drop_table('review_action_items')
    op.drop_constraint('academic_years_college_id_label_key', 'academic_years', type_='unique')
    op.drop_index('idx_academic_years_college', table_name='academic_years')
    op.drop_index('idx_academic_years_current', table_name='academic_years', postgresql_where='(is_current = true)')
    op.alter_column('attendance_records', 'status',
               existing_type=postgresql.ENUM('present', 'absent', 'od', 'medical_leave', 'duty_leave', name='attendance_status'),
               type_=sa.Enum('present', 'absent', 'od', 'medical_leave', 'duty_leave', name='attendancestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'present'::attendance_status"))
    op.drop_constraint('attendance_records_student_id_subject_id_date_period_key', 'attendance_records', type_='unique')
    op.drop_index('idx_att_sem_date', table_name='attendance_records')
    op.drop_index('idx_att_status', table_name='attendance_records', postgresql_where="(status = 'absent'::attendance_status)")
    op.drop_index('idx_att_student_sem', table_name='attendance_records')
    op.drop_index('idx_att_subject_date', table_name='attendance_records')
    op.alter_column('colleges', 'accreditation_type',
               existing_type=postgresql.ENUM('naac', 'nba', 'nirf', 'aicte', 'ugc', 'autonomous', 'none', name='accreditation_type'),
               type_=sa.Enum('naac', 'nba', 'nirf', 'aicte', 'ugc', 'autonomous', 'none', name='accreditationtype'),
               existing_nullable=False,
               existing_server_default=sa.text("'none'::accreditation_type"))
    op.alter_column('colleges', 'nba_programs',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('colleges', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint('departments_college_id_code_key', 'departments', type_='unique')
    op.drop_index('idx_departments_college', table_name='departments')
    op.alter_column('hod_performance_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('hod_performance_metrics_user_id_month_key', 'hod_performance_metrics', type_='unique')
    op.create_index(op.f('ix_hod_performance_metrics_id'), 'hod_performance_metrics', ['id'], unique=False)
    op.alter_column('marks_records', 'exam_type',
               existing_type=postgresql.ENUM('cia1', 'cia2', 'cia3', 'model', 'semester_end', 'practical', 'viva', 'assignment', 'quiz', 'project_review', name='exam_type_enum'),
               type_=sa.Enum('cia1', 'cia2', 'cia3', 'model', 'semester_end', 'practical', 'viva', 'assignment', 'quiz', 'project_review', name='examtypeenum'),
               existing_nullable=False)
    op.drop_index('idx_marks_grade', table_name='marks_records', postgresql_where="((grade)::text = ANY ((ARRAY['F'::character varying, 'U'::character varying, 'Ab'::character varying])::text[]))")
    op.drop_index('idx_marks_student_sem', table_name='marks_records')
    op.drop_index('idx_marks_subject', table_name='marks_records')
    op.drop_constraint('marks_records_student_id_subject_id_semester_id_exam_type_key', 'marks_records', type_='unique')
    op.drop_column('marks_records', 'percentage')
    op.drop_constraint('placement_applications_student_id_drive_id_key', 'placement_applications', type_='unique')
    op.alter_column('placement_drives', 'eligible_departments',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('programs', 'type',
               existing_type=postgresql.ENUM('ug', 'pg', 'diploma', 'certificate', 'phd', name='program_type'),
               type_=sa.Enum('ug', 'pg', 'diploma', 'certificate', 'phd', name='programtype'),
               existing_nullable=False)
    op.drop_index('idx_programs_department', table_name='programs')
    op.alter_column('semesters', 'status',
               existing_type=postgresql.ENUM('upcoming', 'ongoing', 'completed', 'results_published', name='semester_status'),
               type_=sa.Enum('upcoming', 'ongoing', 'completed', 'results_published', name='semesterstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'upcoming'::semester_status"))
    op.drop_index('idx_semesters_ay', table_name='semesters')
    op.drop_index('idx_semesters_program', table_name='semesters')
    op.drop_index('idx_semesters_status', table_name='semesters')
    op.drop_constraint('semesters_academic_year_id_program_id_semester_number_key', 'semesters', type_='unique')
    op.alter_column('staff_performance_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('staff_performance_metrics_user_id_month_key', 'staff_performance_metrics', type_='unique')
    op.create_index(op.f('ix_staff_performance_metrics_id'), 'staff_performance_metrics', ['id'], unique=False)
    op.alter_column('students', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', 'prefer_not_to_say', name='gender_enum'),
               type_=sa.Enum('male', 'female', 'other', 'prefer_not_to_say', name='genderenum'),
               existing_nullable=True)
    op.alter_column('students', 'current_semester',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('students', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'detained', 'arrear', 'lateral_entry', 'transferred_in', 'transferred_out', 'passed_out', 'discontinued', name='student_status'),
               type_=sa.Enum('active', 'inactive', 'detained', 'arrear', 'lateral_entry', 'transferred_in', 'transferred_out', 'passed_out', 'discontinued', name='studentstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::student_status"))
    op.alter_column('students', 'risk_flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('idx_students_college', table_name='students')
    op.drop_index('idx_students_department', table_name='students')
    op.drop_index('idx_students_name_trgm', table_name='students', postgresql_using='gin')
    op.drop_index('idx_students_program', table_name='students')
    op.drop_index('idx_students_risk', table_name='students', postgresql_where='(risk_score > (50)::numeric)')
    op.drop_index('idx_students_status', table_name='students')
    op.drop_constraint('students_college_id_roll_number_key', 'students', type_='unique')
    op.alter_column('subjects', 'type',
               existing_type=postgresql.ENUM('theory', 'practical', 'theory_cum_practical', 'project', 'seminar', 'internship', 'mooc', 'audit_course', name='subject_type'),
               type_=sa.Enum('theory', 'practical', 'theory_cum_practical', 'project', 'seminar', 'internship', 'mooc', 'audit_course', name='subjecttype'),
               existing_nullable=False,
               existing_server_default=sa.text("'theory'::subject_type"))
    op.drop_index('idx_subjects_department', table_name='subjects')
    op.drop_index('idx_subjects_program', table_name='subjects')
    op.drop_index('idx_subjects_semester', table_name='subjects')
    op.drop_constraint('subjects_department_id_code_regulations_key', 'subjects', type_='unique')
    op.drop_column('subjects', 'is_lab')
    op.drop_column('subjects', 'total_hours')
    op.alter_column('users', 'experience_years',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'college_admin', 'principal', 'hod', 'faculty', 'staff', 'student', name='user_role'),
               type_=sa.Enum('admin', 'college_admin', 'principal', 'hod', 'faculty', 'staff', 'student', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'faculty'::user_role"))
    op.alter_column('users', 'research_output_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'feedback_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_users_college', table_name='users')
    op.drop_index('idx_users_department', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_constraint('users_college_id_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_college_id_email_key', 'users', ['college_id', 'email'])
    op.create_index('idx_users_role', 'users', ['college_id', 'role'], unique=False)
    op.create_index('idx_users_department', 'users', ['department_id'], unique=False)
    op.create_index('idx_users_college', 'users', ['college_id'], unique=False)
    op.alter_column('users', 'preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('users', 'feedback_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('users', 'research_output_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'college_admin', 'principal', 'hod', 'faculty', 'staff', 'student', name='userrole'),
               type_=postgresql.ENUM('admin', 'college_admin', 'principal', 'hod', 'faculty', 'staff', 'student', name='user_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'faculty'::user_role"))
    op.alter_column('users', 'experience_years',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.add_column('subjects', sa.Column('total_hours', sa.SMALLINT(), sa.Computed('((lecture_hours + tutorial_hours) + practical_hours)', persisted=True), autoincrement=False, nullable=True))
    op.add_column('subjects', sa.Column('is_lab', sa.BOOLEAN(), sa.Computed('(practical_hours > 0)', persisted=True), autoincrement=False, nullable=True))
    op.create_unique_constraint('subjects_department_id_code_regulations_key', 'subjects', ['department_id', 'code', 'regulations'])
    op.create_index('idx_subjects_semester', 'subjects', ['program_id', 'semester_number'], unique=False)
    op.create_index('idx_subjects_program', 'subjects', ['program_id'], unique=False)
    op.create_index('idx_subjects_department', 'subjects', ['department_id'], unique=False)
    op.alter_column('subjects', 'type',
               existing_type=sa.Enum('theory', 'practical', 'theory_cum_practical', 'project', 'seminar', 'internship', 'mooc', 'audit_course', name='subjecttype'),
               type_=postgresql.ENUM('theory', 'practical', 'theory_cum_practical', 'project', 'seminar', 'internship', 'mooc', 'audit_course', name='subject_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'theory'::subject_type"))
    op.create_unique_constraint('students_college_id_roll_number_key', 'students', ['college_id', 'roll_number'])
    op.create_index('idx_students_status', 'students', ['college_id', 'status'], unique=False)
    op.create_index('idx_students_risk', 'students', ['college_id', sa.text('risk_score DESC')], unique=False, postgresql_where='(risk_score > (50)::numeric)')
    op.create_index('idx_students_program', 'students', ['program_id', 'batch'], unique=False)
    op.create_index('idx_students_name_trgm', 'students', ['name'], unique=False, postgresql_using='gin')
    op.create_index('idx_students_department', 'students', ['department_id', 'current_semester'], unique=False)
    op.create_index('idx_students_college', 'students', ['college_id'], unique=False)
    op.alter_column('students', 'risk_flags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('students', 'status',
               existing_type=sa.Enum('active', 'inactive', 'detained', 'arrear', 'lateral_entry', 'transferred_in', 'transferred_out', 'passed_out', 'discontinued', name='studentstatus'),
               type_=postgresql.ENUM('active', 'inactive', 'detained', 'arrear', 'lateral_entry', 'transferred_in', 'transferred_out', 'passed_out', 'discontinued', name='student_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::student_status"))
    op.alter_column('students', 'current_semester',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('students', 'gender',
               existing_type=sa.Enum('male', 'female', 'other', 'prefer_not_to_say', name='genderenum'),
               type_=postgresql.ENUM('male', 'female', 'other', 'prefer_not_to_say', name='gender_enum'),
               existing_nullable=True)
    op.drop_index(op.f('ix_staff_performance_metrics_id'), table_name='staff_performance_metrics')
    op.create_unique_constraint('staff_performance_metrics_user_id_month_key', 'staff_performance_metrics', ['user_id', 'month'])
    op.alter_column('staff_performance_metrics', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('semesters_academic_year_id_program_id_semester_number_key', 'semesters', ['academic_year_id', 'program_id', 'semester_number'])
    op.create_index('idx_semesters_status', 'semesters', ['status'], unique=False)
    op.create_index('idx_semesters_program', 'semesters', ['program_id'], unique=False)
    op.create_index('idx_semesters_ay', 'semesters', ['academic_year_id'], unique=False)
    op.alter_column('semesters', 'status',
               existing_type=sa.Enum('upcoming', 'ongoing', 'completed', 'results_published', name='semesterstatus'),
               type_=postgresql.ENUM('upcoming', 'ongoing', 'completed', 'results_published', name='semester_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'upcoming'::semester_status"))
    op.create_index('idx_programs_department', 'programs', ['department_id'], unique=False)
    op.alter_column('programs', 'type',
               existing_type=sa.Enum('ug', 'pg', 'diploma', 'certificate', 'phd', name='programtype'),
               type_=postgresql.ENUM('ug', 'pg', 'diploma', 'certificate', 'phd', name='program_type'),
               existing_nullable=False)
    op.alter_column('placement_drives', 'eligible_departments',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.create_unique_constraint('placement_applications_student_id_drive_id_key', 'placement_applications', ['student_id', 'drive_id'])
    op.add_column('marks_records', sa.Column('percentage', sa.NUMERIC(precision=5, scale=2), sa.Computed('round(((100.0 * marks_obtained) / NULLIF(max_marks, (0)::numeric)), 2)', persisted=True), autoincrement=False, nullable=True))
    op.create_unique_constraint('marks_records_student_id_subject_id_semester_id_exam_type_key', 'marks_records', ['student_id', 'subject_id', 'semester_id', 'exam_type'])
    op.create_index('idx_marks_subject', 'marks_records', ['subject_id', 'semester_id'], unique=False)
    op.create_index('idx_marks_student_sem', 'marks_records', ['student_id', 'semester_id'], unique=False)
    op.create_index('idx_marks_grade', 'marks_records', ['grade'], unique=False, postgresql_where="((grade)::text = ANY ((ARRAY['F'::character varying, 'U'::character varying, 'Ab'::character varying])::text[]))")
    op.alter_column('marks_records', 'exam_type',
               existing_type=sa.Enum('cia1', 'cia2', 'cia3', 'model', 'semester_end', 'practical', 'viva', 'assignment', 'quiz', 'project_review', name='examtypeenum'),
               type_=postgresql.ENUM('cia1', 'cia2', 'cia3', 'model', 'semester_end', 'practical', 'viva', 'assignment', 'quiz', 'project_review', name='exam_type_enum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_hod_performance_metrics_id'), table_name='hod_performance_metrics')
    op.create_unique_constraint('hod_performance_metrics_user_id_month_key', 'hod_performance_metrics', ['user_id', 'month'])
    op.alter_column('hod_performance_metrics', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_departments_college', 'departments', ['college_id'], unique=False)
    op.create_unique_constraint('departments_college_id_code_key', 'departments', ['college_id', 'code'])
    op.alter_column('colleges', 'settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('colleges', 'nba_programs',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('colleges', 'accreditation_type',
               existing_type=sa.Enum('naac', 'nba', 'nirf', 'aicte', 'ugc', 'autonomous', 'none', name='accreditationtype'),
               type_=postgresql.ENUM('naac', 'nba', 'nirf', 'aicte', 'ugc', 'autonomous', 'none', name='accreditation_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'none'::accreditation_type"))
    op.create_index('idx_att_subject_date', 'attendance_records', ['subject_id', 'date'], unique=False)
    op.create_index('idx_att_student_sem', 'attendance_records', ['student_id', 'semester_id'], unique=False)
    op.create_index('idx_att_status', 'attendance_records', ['status', 'date'], unique=False, postgresql_where="(status = 'absent'::attendance_status)")
    op.create_index('idx_att_sem_date', 'attendance_records', ['semester_id', 'date'], unique=False)
    op.create_unique_constraint('attendance_records_student_id_subject_id_date_period_key', 'attendance_records', ['student_id', 'subject_id', 'date', 'period'])
    op.alter_column('attendance_records', 'status',
               existing_type=sa.Enum('present', 'absent', 'od', 'medical_leave', 'duty_leave', name='attendancestatus'),
               type_=postgresql.ENUM('present', 'absent', 'od', 'medical_leave', 'duty_leave', name='attendance_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'present'::attendance_status"))
    op.create_index('idx_academic_years_current', 'academic_years', ['college_id', 'is_current'], unique=False, postgresql_where='(is_current = true)')
    op.create_index('idx_academic_years_college', 'academic_years', ['college_id'], unique=False)
    op.create_unique_constraint('academic_years_college_id_label_key', 'academic_years', ['college_id', 'label'])
    op.create_table('review_action_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='review_action_items_owner_id_fkey'),
    sa.ForeignKeyConstraint(['review_id'], ['department_reviews.id'], name='review_action_items_review_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='review_action_items_pkey')
    )
    op.create_index('ix_review_action_items_id', 'review_action_items', ['id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('last_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_sessions_pkey')
    )
    op.create_index('idx_chat_user', 'chat_sessions', ['user_id', sa.text('updated_at DESC')], unique=False)
    op.create_index('idx_chat_session', 'chat_sessions', ['session_key'], unique=False)
    op.create_table('accreditation_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('college_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('nba_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('naac_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('documentation_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name='accreditation_metrics_college_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='accreditation_metrics_pkey')
    )
    op.create_index('ix_accreditation_metrics_id', 'accreditation_metrics', ['id'], unique=False)
    op.create_table('communications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipient_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('recipient_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='communications_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='communications_pkey')
    )
    op.create_index('ix_communications_id', 'communications', ['id'], unique=False)
    op.create_table('student_risk_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('dropout_probability', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('arrear_probability', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='student_risk_scores_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='student_risk_scores_pkey')
    )
    op.create_index('ix_student_risk_scores_id', 'student_risk_scores', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('college_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("action::text = ANY (ARRAY['INSERT'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying, 'SELECT_EXPORT'::character varying]::text[])", name='audit_logs_action_check'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name='audit_logs_college_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('idx_audit_user', 'audit_logs', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_audit_table', 'audit_logs', ['table_name', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_audit_college', 'audit_logs', ['college_id', sa.text('created_at DESC')], unique=False)
    op.create_table('exam_schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exam_type', postgresql.ENUM('cia1', 'cia2', 'cia3', 'model', 'semester_end', 'practical', 'viva', 'assignment', 'quiz', 'project_review', name='exam_type_enum'), autoincrement=False, nullable=False),
    sa.Column('exam_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('venue', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('total_marks', sa.SMALLINT(), server_default=sa.text('100'), autoincrement=False, nullable=False),
    sa.Column('pass_marks', sa.SMALLINT(), server_default=sa.text('50'), autoincrement=False, nullable=False),
    sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_cancelled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name='exam_schedules_semester_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='exam_schedules_subject_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='exam_schedules_pkey'),
    sa.UniqueConstraint('semester_id', 'subject_id', 'exam_type', name='exam_schedules_semester_id_subject_id_exam_type_key')
    )
    op.create_index('idx_exams_semester', 'exam_schedules', ['semester_id'], unique=False)
    op.create_index('idx_exams_date', 'exam_schedules', ['exam_date'], unique=False)
    op.create_table('executive_insights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('college_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name='executive_insights_college_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='executive_insights_pkey')
    )
    op.create_index('ix_executive_insights_id', 'executive_insights', ['id'], unique=False)
    op.create_table('program_semesters',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('program_semesters_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('semester_number', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('min_credits', sa.SMALLINT(), server_default=sa.text('18'), autoincrement=False, nullable=False),
    sa.Column('max_credits', sa.SMALLINT(), server_default=sa.text('26'), autoincrement=False, nullable=False),
    sa.Column('regulations', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name='program_semesters_program_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='program_semesters_pkey'),
    sa.UniqueConstraint('program_id', 'semester_number', name='program_semesters_program_id_semester_number_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('institution_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('college_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('academic_health', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('attendance_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('pass_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('placement_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name='institution_metrics_college_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='institution_metrics_pkey')
    )
    op.create_index('ix_institution_metrics_id', 'institution_metrics', ['id'], unique=False)
    op.create_table('student_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doc_type', postgresql.ENUM('aadhaar', 'pan', 'transfer_certificate', 'conduct_certificate', 'migration_certificate', 'mark_sheet_10', 'mark_sheet_12', 'ug_degree', 'community_certificate', 'income_certificate', 'medical_certificate', 'photo', 'signature', 'other', name='document_type'), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_size_kb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='student_documents_student_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name='student_documents_verified_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='student_documents_pkey')
    )
    op.create_index('idx_docs_student', 'student_documents', ['student_id'], unique=False)
    op.create_table('at_risk_snapshots',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('triggered_by', sa.VARCHAR(length=50), server_default=sa.text("'scheduled_scan'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name='at_risk_snapshots_semester_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='at_risk_snapshots_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='at_risk_snapshots_pkey'),
    sa.UniqueConstraint('student_id', 'semester_id', 'snapshot_date', name='at_risk_snapshots_student_id_semester_id_snapshot_date_key')
    )
    op.create_index('idx_risk_student', 'at_risk_snapshots', ['student_id', 'semester_id'], unique=False)
    op.create_index('idx_risk_high', 'at_risk_snapshots', [sa.text('risk_score DESC')], unique=False, postgresql_where='(risk_score >= (60)::numeric)')
    op.create_index('idx_risk_date', 'at_risk_snapshots', [sa.text('snapshot_date DESC')], unique=False)
    op.create_table('faculty_subject_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('assigned_on', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name='faculty_subject_assignments_semester_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='faculty_subject_assignments_subject_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='faculty_subject_assignments_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='faculty_subject_assignments_pkey'),
    sa.UniqueConstraint('user_id', 'subject_id', 'semester_id', name='faculty_subject_assignments_user_id_subject_id_semester_id_key')
    )
    op.create_index('idx_fsa_user', 'faculty_subject_assignments', ['user_id'], unique=False)
    op.create_index('idx_fsa_subject', 'faculty_subject_assignments', ['subject_id'], unique=False)
    op.create_index('idx_fsa_sem', 'faculty_subject_assignments', ['semester_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('college_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('attendance_alert', 'marks_alert', 'at_risk_flag', 'report_ready', 'upload_complete', 'exam_schedule', 'timetable_change', 'general', name='notification_type'), server_default=sa.text("'general'::notification_type"), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('action_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name='notifications_college_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('idx_notif_user', 'notifications', ['user_id', 'is_read', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_notif_unread', 'notifications', ['user_id'], unique=False, postgresql_where='(is_read = false)')
    op.create_table('department_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='department_reviews_department_id_fkey'),
    sa.ForeignKeyConstraint(['principal_id'], ['users.id'], name='department_reviews_principal_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='department_reviews_pkey')
    )
    op.create_index('ix_department_reviews_id', 'department_reviews', ['id'], unique=False)
    op.create_table('timetable_slots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('faculty_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day', postgresql.ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='day_of_week'), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('room', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('period_label', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('section', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.CheckConstraint('start_time < end_time', name='tt_time_order'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name='timetable_slots_faculty_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name='timetable_slots_semester_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='timetable_slots_subject_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='timetable_slots_pkey')
    )
    op.create_index('idx_timetable_semester', 'timetable_slots', ['semester_id'], unique=False)
    op.create_index('idx_timetable_room', 'timetable_slots', ['room', 'day', 'start_time'], unique=False)
    op.create_index('idx_timetable_faculty', 'timetable_slots', ['faculty_id', 'day'], unique=False)
    op.create_table('student_interventions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='student_interventions_owner_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='student_interventions_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='student_interventions_pkey')
    )
    op.create_index('ix_student_interventions_id', 'student_interventions', ['id'], unique=False)
    op.create_table('semester_enrollments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('enrolled', 'dropped', 'detained', 'completed', 'arrear_registered', name='enrollment_status'), server_default=sa.text("'enrolled'::enrollment_status"), autoincrement=False, nullable=False),
    sa.Column('section', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('enrolled_on', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name='semester_enrollments_semester_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='semester_enrollments_student_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='semester_enrollments_subject_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='semester_enrollments_pkey'),
    sa.UniqueConstraint('student_id', 'semester_id', 'subject_id', name='semester_enrollments_student_id_semester_id_subject_id_key')
    )
    op.create_index('idx_enrollments_student', 'semester_enrollments', ['student_id'], unique=False)
    op.create_index('idx_enrollments_sem', 'semester_enrollments', ['semester_id', 'subject_id'], unique=False)
    op.create_table('department_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('attendance_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('pass_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('health_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('risk_students_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='department_metrics_department_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='department_metrics_pkey')
    )
    op.create_index('ix_department_metrics_id', 'department_metrics', ['id'], unique=False)
    op.create_table('syllabus_units',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('program_semester_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_number', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('topics', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('teaching_hours', sa.SMALLINT(), server_default=sa.text('6'), autoincrement=False, nullable=False),
    sa.Column('learning_outcomes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('co_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('cognitive_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reference_books', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['program_semester_id'], ['program_semesters.id'], name='syllabus_units_program_semester_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='syllabus_units_subject_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='syllabus_units_pkey'),
    sa.UniqueConstraint('subject_id', 'unit_number', name='syllabus_units_subject_id_unit_number_key')
    )
    op.create_index('idx_syllabus_subject', 'syllabus_units', ['subject_id'], unique=False)
    # ### end Alembic commands ###
